GOOGLE_API_KEY: <YOUR_GOOGLE_API_KEY>
GOOGLE_CSE_ID: <YOUR_GOOGLE_CSE_ID>
OPENAI_API_KEY: <YOUR_OPENAI_API_KEY>
SPOTIPY_CLIENT_ID: <YOUR_SPOTIPY_CLIENT_ID>
SPOTIPY_CLIENT_SECRET: <YOUR_SPOTIPY_CLIENT_SECRET>
SPOTIPY_REDIRECT_URI: <YOUR_SPOTIPY_REDIRECT_URI>
